### ISSUE TITLE
Facing error

### ISSUE THREAD

**Issue by govindasomani** [pkjmesra/whatsapp-bot#1]
![Screenshot_20210602-025141.jpg](https://user-images.githubusercontent.com/83778224/120392234-d77b1d00-c34d-11eb-8d21-eb0989f61896.jpg)

Facing this error while running install.sh

**Comment by pkjmesra** [comment]
You'd need to run git clone https://github.com/pkjmesra/whatsapp-bot first. then cd whatsapp-bot/pkBot

**Comment by govindasomani** [comment]
![Screenshot_20210602-185138__01.jpg](https://user-images.githubusercontent.com/83778224/120488112-2075b480-c3d4-11eb-8614-a51fce131ac8.jpg)

Did the steps you mentioned.. another error now..

**Comment by pkjmesra** [comment]
You need to remove the pre-existing directory
By going back to the previous directory
cd ..
Then remove the directory
rm -rf whatsapp-bot
Then you need to clone and redo the steps.
