### ISSUE TITLE
Other mobile number's booking with whatsapp bot in my phone

### ISSUE THREAD

**Issue by archit-va** [pkjmesra/whatsapp-bot#2]
How can I use other's mobile no. For booking but use the bot from my phone?

**Comment by pkjmesra** [comment]
On your computer whatever number you logged in to WhatsApp with, by scanning the QR code, that number becomes the host.

Any other mobile number who want to book, will need to send *subscribe* to the host whatsapp. After that, the bot will ask all the details it needs and begin polling the cowin server.

When a slot is available, it will notify via whatsapp to the subscriber, send OTP and read CAPTCHA on its own before going ahead with booking.

If the host wants to book for oneself, the host will also need to send *subscribe* message to itself.

Hope that helps.
